### ISSUE TITLE
backtick char does not open the interface on my French keyboard

### ISSUE THREAD

**Issue by yafred** [iandunn/quick-navigation-interface#1]
Hi,
Thanks for this plugin

Unfortunately, the backtick does not work as expected; on a French keyboard, it's a dead key to accentuate characters.

I think esc key would be a better default key to open the interface (that can be closed with the mouse)

**Comment by iandunn** [comment]
Ah, that sucks. I'm not sure if it'd be good to change the default key at this point, but I'll think about.

It's easy to change the key to something else, though. The FAQ has some details on that.

**Comment by yafred** [comment]
Sorry I did not read the FAQ: I just edited https://github.com/iandunn/quick-navigation-interface/blob/master/classes/quick-navigation-interface.php#L31 to try the plugin

My point is that unless you add an option screen or the user writes some code, the first contact with the  plugin is frustrating if you don't have the right keyboard ... that's a pity.

You're right about NOT changing the default value ... instead, you could add another key (as universal as possible) to open the search interface ... I'll think about it

**Comment by iandunn** [comment]
Ah, yeah, adding a second key is good idea.

I want to get some more feedback from a wide range of users first, though, so I don't add a key that's good for French keyboard, but bad for an Arabic or Russian or Chinese keyboard.

**Comment by iandunn** [comment]
The backtick also [doesn't work reliable on Spanish keyboards](https://wordpress.org/support/topic/problem-in-chrome-4).

**Comment by iandunn** [comment]
`g` seems to be commonly used for this, e.g., GitHub, Calypso.

**Comment by iandunn** [comment]
`/` is also commonly used (Trello, Remember the Milk)

**Comment by iandunn** [comment]
The \` character also conflicts with Gutenberg, which uses control+` to navigate to the next part of the editor.

**Comment by tbnv** [comment]
On my French Apple keyboard (azerty), the navigation is triggered by the `@` character. Which is pretty cool.

I see the `esc` was suggested above. UX-wise I would certainly not use that key to open the navigation, because its meaning is... juste the opposite of "open". 🙂

**Comment by iandunn** [comment]
🤔 

I'm thinking that `g` might be the best option. Here's some of the things I've read related to this:

* https://medium.com/@sashika/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee#.cbjvagkdg
* https://ux.stackexchange.com/questions/76405/what-are-conventions-for-keyboard-shortcuts-in-windows-and-osx 
* http://www.hanselman.com/blog/TheWebIsTheNewTerminalAreYouUsingTheWebsKeyboardShortcutsAndHotkeys.aspx
* https://docs.google.com/spreadsheets/d/1nK1frKawxV7aboWOJbbslbIqBGoLY7gqKvfwqENj2yE/edit#gid=0

**Comment by iandunn** [comment]
Once v1.0 comes out, `g` will also open the interface, in addition to ``` ` ```.
